mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('jsi18n/', cache_page(3600)(JavaScriptCatalog.as_view(packages=['formset'])), name='javascript-catalog'),
    path("select2/", include("django_select2.urls")),
    path("", include("secondapp.urls", namespace="secondapp")),

]



from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("polls/", views.IndexView.as_view(), name="index"),
    path("polls/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("polls/<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("polls/<int:question_id>/vote/", views.vote, name="vote"),
]

secondapp/urls.py
from django.urls import path, include


from . import views

app_name = 'secondapp'

urlpatterns = [




    path("signup/", views.SignUp.as_view(), name="signup"),

    path("<str:username>/person_form2/", views.PersonUpdateView.as_view(), name="person_update"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("login/", views.UserLoginView.as_view(), name="login"),

    path("home/", views.HomeView.as_view(), name="home"),

    path("", views.IndexView.as_view(), name="index2"),
    path("organization_form/", views.OrganizationCreateView.as_view(), name="org_create"),

    path("<str:username>/dashboard/", views.OrganizationDashboard.as_view(), name="org_dashboard"),
    path("<str:username>/members/", views.OrgMemberListView.as_view(), name="org_member_list"),
    path("<str:username>/members/add/", views.OrgMemberAddView.as_view(),name="org_member_add"),
    path("<str:username>/members/edit/<int:pk>/", views.OrgMemberEditView.as_view(), name="org_member_edit"),

    path("<str:username>/songs/", views.SongListView.as_view(), name="song_dashboard"),
    path("<str:username>/songs/create/", views.SongCreateView.as_view(), name="song_form2"),
    path("<str:username>/songs/<int:pk>/", views.SongDetailView.as_view(), name="song_page"),
    path("<str:username>/songs/<int:pk>/update/", views.SongUpdateView.as_view(), name="song_form2"),
    path("<str:username>/songs/<int:pk>/delete/", views.SongDeleteView.as_view(), name="song_delete"),
    path("skill/", views.SkillListAndCreateView.as_view(), name="skill"),

#    path("", include("django.contrib.auth.urls")),

    # path("login/", views.AccountLoginView.as_view(), name="login"),
    #
    #
    # path("rehearsal/", views.RehearsalListView.as_view(), name="rehearsal_list"),
    # path("rehearsal/<int:pk>/", views.RehearsalDetailView.as_view(), name="rehearsal_detail"),
    # path("rehearsal/create/", views.RehearsalCreateView.as_view(), name="rehearsal_form"),
    # path("rehearsal/<int:pk>/update/", views.RehearsalUpdateView.as_view(), name="rehearsal_update"),
    # path("rehearsal/<int:pk>/confirm/", views.RehearsalDeleteView.as_view(), name="rehearsal_delete"),
    #
    # path("song/", views.SongListView.as_view(), name="song_list"),
    # path("song/<int:pk>/", views.SongDetailView.as_view(), name="song_detail"),
    # path("song/create/", views.SongCreateView.as_view(), name="song_form"),
    # path("song/<int:pk>/update/", views.SongUpdateView.as_view(), name="song_update"),
    # path("song/<int:pk>/delete/", views.SongDeleteView.as_view(), name="song_delete"),

    # path("tag/", views.TagListAndCreateView.as_view(), name="tag"),
    #
    # path("import/", views.ImportFileListView.as_view(), name="import_list"),
    # path("import/upload/", views.ImportFileFormView.as_view(), name="import_upload"),
    # path("import/<int:pk>/", views.ImportFileDetailView.as_view(), name="import_detail"),
    #
    # path("ensemble/", views.EnsembleListView.as_view(), name="ensemble_list"),
    # path("ensemble/<int:pk>/", views.EnsembleDetailView.as_view(), name="ensemble_detail"),
    # path("ensemble/create/", views.EnsembleCreateView.as_view(), name="ensemble_form"),
    # path("ensemble/<int:pk>/update/", views.EnsembleUpdateView.as_view(), name="ensemble_update"),
    # path("ensemble/<int:pk>/delete/", views.EnsembleDeleteView.as_view(), name="ensemble_delete"),
    #
    # path("<str:role>/", views.PersonListView.as_view(), name="person_list"),
    # path("<str:role>/<int:pk>/", views.PersonDetailView.as_view(), name="person_detail"),
    # path("<str:role>/create/", views.PersonCreateView.as_view(), name="person_form"),
    # path("<str:role>/<int:pk>/update/", views.PersonUpdateView.as_view(), name="person_update"),
    # path("<str:role>/<int:pk>/delete/", views.PersonDeleteView.as_view(), name="person_delete"),
    #
    # path("<str:role>/<int:pk>/activity/create/", views.ActivityCreateView.as_view(), name="activity_form"),
    # path("<str:role>/<int:pk>/activity/update/", views.ActivityUpdateView.as_view(), name="activity_update"),
    # path("<str:role>/<int:pk>/activity/delete/", views.ActivityDeleteView.as_view(), name="activity_confirm_delete"),

]

secondapp/views.py
# views.py
import csv
from dataclasses import field
from fileinput import filename
import sqlite3

from django.contrib.auth import logout
from django.shortcuts import redirect
from django.core.files.uploadedfile import UploadedFile
from django.core.exceptions import PermissionDenied
from django.db import connection
from django.http import HttpRequest, HttpResponse, Http404, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.template.context_processors import request
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.sessions.models import Session
from datetime import datetime, timedelta, date
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, View, FormView, TemplateView
from django.views.generic.edit import DeleteView
from django.db.models import Q, Prefetch
from django.apps import apps
from django.conf import settings
import os
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordContextMixin
from django.db import transaction
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify


import datetime
from django.views.generic import FormView, TemplateView
from django.shortcuts import redirect
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import OrgMemberForm
from .models import Organization, Person, Membership, MembershipPeriod, Role, PersonSkill, PersonQuerySet

# from .forms import RehearsalForm, Member, ComposerForm, PoetForm, ArrangerForm, MusicianForm, SongForm, TagForm, PersonForm, EnsembleForm, ActivityForm, ImportFileForm
# from .models import Rehearsal, Member, Composer, Poet, Arranger, Musician, Song, Ensemble, Activity, Conductor, ImportFile
# from .mixins import TagListAndCreateMixin, PersonRoleMixin, BreadcrumbMixin, LoginRequiredMixin

from .models import CustomUser, Organization, Person, Membership, Role, Song, Skill
from .forms import RegisterForm, OrganizationForm, PersonForm, SongForm, SkillForm
from .forms import CustomUserCreationForm
from .mixins import RoleRequiredMixin, SkillListAndCreateMixin
from .permissions import AccessControl


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "secondapp/signup.html"

    def form_valid(self, form):
        response = super().form_valid(form) #save the new user first

        Person.objects.create(
        user=self.object,
        email=self.object.email,
        first_name="",
        last_name="",
        )

        return response


class UserLogoutView(LogoutView):
    next_page = reverse_lazy("secondapp:home")


class UserLoginView(LoginView):
    template_name = "registration/login.html"


class HomeView(generic.TemplateView):
    template_name = "secondapp/home.html"



@method_decorator(login_required, name='dispatch')
class PersonUpdateView(UpdateView):
    template_name = "secondapp/person_form2.html"
    form_class = PersonForm
    context_object_name = "person_create"
    success_url = reverse_lazy("secondapp:home")

    def get_object(self, queryset=None):
        return Person.objects.get(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user = self.request.user
        organization = getattr(user, "organization", None)
        user_role = getattr(user, "role", None)

        if self.object.user:
            self.object.user.email = self.object.email
            self.object.user.save()

        # Admin can make new persons
        if organization and user_role == Role.ADMIN:
            self.object.user = None
            self.object.save()
            Membership.objects.create(
                organization=self.organization,
                person=self.object,
                role=Role.MEMBER,
                # is_active=True
            )
        else:
            # non-admin access
            self.object.user = self.request.user
            self.object.save()

        return redirect(self.get_success_url())


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "secondapp/index2.html"
    model = Person

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context["memberships"] = Membership.objects.filter(person__user=user).select_related("organization")
        return context


@method_decorator(login_required, name='dispatch')
class OrganizationDashboard(TemplateView):
    """Home page for specific organizations."""
    template_name = "secondapp/org_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        username = self.kwargs["username"]
        organization = get_object_or_404(
            Organization,
            user__username=username
        )

        context["organization"] = organization
        context["memberships"] = Membership.objects.filter(
            organization=organization
        )

        return context


@method_decorator(login_required, name='dispatch')
class OrganizationCreateView(CreateView):
    template_name = "secondapp/organization_form.html"
    form_class = OrganizationForm
    context_object_name = "org_create"
    success_url = reverse_lazy("secondapp:home")

    def form_valid(self, form):
        # atomic transaction - creates everything at once:
        with transaction.atomic():
            the_admin = Person.objects.filter(user=self.request.user).first()

            # create auth account for org
            org_user = CustomUser.objects.create(
                username=slugify(form.cleaned_data["name"]),
                email=form.cleaned_data["email"],
            )
            org_user.set_unusable_password()
            org_user.save()

            # create org
            organization = form.save(commit=False)
            organization.user = org_user
            organization.save()

            # create admin person of the org
            person_admin = Person.objects.create(
                user=organization.user,    # this Person belongs to the organization
                owner=the_admin,    #  this person is claimed by the creator of the organization
                email=the_admin.email,
                first_name=the_admin.first_name,
                last_name=the_admin.last_name,
            )

            # make an admin role into membership
            Membership.objects.create(
                organization=organization,
                person=person_admin,
                role_id=Role.ADMIN,
            )

            # track the admin into period
            MembershipPeriod.objects.create(
                organization=organization,
                person=person_admin,
                role_id=Role.ADMIN,
                started_at=datetime.date.today()
            )

        return super().form_valid(form)


class OrgMemberMixin(RoleRequiredMixin):
    """Mixin for organization member views."""
    allowed_roles = [Role.ADMIN, Role.MEMBER]

    def dispatch(self, request, *args, **kwargs):
        # Get username from URL
        username = self.kwargs.get("username")

        # Find the organization
        self.organization = get_object_or_404(Organization, user__username=username)

        # Get the user's Person
        person = request.user.persons.first()

        # Get the user's role in this organization
        self.user_role = self.organization.get_role(request.user)
        if not self.role_allowed(self.user_role):
            raise PermissionDenied(f"Your role '{self.user_role}' does not have access.")

        return super().dispatch(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class OrgMemberListView(OrgMemberMixin, ListView):
    """Shows all members of an organization."""
    template_name = "secondapp/org_member_list.html"
    context_object_name = "members"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        username = self.kwargs["username"]
        self.organization = get_object_or_404(Organization, user__username=username)

    def get_queryset(self):
        # Get filtered persons based on access control
        return AccessControl.get_visible_members(
            self.request.user,  # self.request.user = the individual person browsing
            self.organization  # self.organization = the org being viewed
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["organization"] = self.organization
        return context


@method_decorator(login_required, name='dispatch')
class OrgMemberAddView(OrgMemberMixin, FormView):
    """Add new member."""
    template_name = "secondapp/org_member_form.html"
    form_class = OrgMemberForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["page_title"] = f"Add Member to {self.organization.name}"
        return context

    def form_valid(self, form):
        with transaction.atomic():
            # 1. create new person
            person = self._create_person(form)

            # 2. add roles into membership

secondapp/templates/secondapp/import_detail.html
{% extends "secondapp/base.html" %}
{% block title %}Import detail{% endblock %}
{% block content %}
<h1>Preview of import:</h1>


{% endblock %}

secondapp/templates/secondapp/import_list.html
{% extends "secondapp/base.html" %}
{% block title %}Import{% endblock %}
{% block content %}

<div>
    <a href="{% url 'secondapp:import_upload' %}"><button type="button">+ New Upload +</button></a><br><br>
</div>
<h2>Imports:</h2>
<table>
    <tr>
        <th>Title:</th>
        <th>Date:</th>
    </tr>
    {% for import in import_list %}
        <tr>
            <td><a href="{% url 'secondapp:import_detail' import.pk %}">{{ import.name }}
                {{ import.updated_at }}</a>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

secondapp/templates/secondapp/index.html
<!--{% extends "secondapp/base.html" %}-->

<!--{% block title %}index{% endblock %}-->

<!--{% block content %}-->
<!--<h1> Index.html </h1>-->

<!--&lt;!&ndash;  "HAPPENING NOW" Feature &ndash;&gt;-->
<!--{% if happening_now %}-->
<!--    <div class="happening-now-banner">-->
<!--        <div class="urgent-alert">-->
<!--            <h2> REHEARSAL HAPPENING NOW! </h2>-->
<!--            <div class="happening-details">-->
<!--                <p><a href="{% url 'secondapp:rehearsal_detail' happening_now.pk %}">-->
<!--                 Started: {{ happening_now.calendar|date:"j b Y, G:i" }}</a></p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--{% endif %}-->
<!--<h2>Upcoming rehearsals:</h2>-->
<!--<div class="rehearsal-table">-->
<!--    <table>-->
<!--        <tr>-->
<!--            <th> calendar </th>-->
<!--            <th> missing </th>-->
<!--        </tr>-->
<!--        {% for rehearsal in upcoming_rehearsals %}-->
<!--        <tr>-->
<!--            <td><a href="{% url 'secondapp:rehearsal_detail' rehearsal.pk %}"> {{ rehearsal.calendar|date:"j b Y, G:i" }} </td>-->
<!--            <td> {% for member in rehearsal.member_status.missing %} {{ member.first_name }}, {% endfor %}</a></td>-->
<!--        </tr>-->
<!--        {% empty %} Empty calendar.-->
<!--        {% endfor %}-->
<!--    </table>-->
<!--</div>-->
<!--<h2>Past rehearsals:</h2>-->
<!--<div class="rehearsal-table">-->
<!--    <table>-->
<!--        <tr>-->
<!--            <th> calendar </th>-->
<!--            <th> not present </th>-->
<!--        </tr>-->
<!--        {% for rehearsal in past_rehearsals %}-->
<!--        <tr>-->
<!--            <td><a href="{% url 'secondapp:rehearsal_detail' rehearsal.pk %}"> {{ rehearsal.calendar|date:"j b Y, G:i" }} </td>-->
<!--            <td> {% for member in rehearsal.member_status.missing %} {{ member.first_name }}, {% endfor %}</a></td>-->
<!--        </tr>-->
<!--        {% empty %} Empty calendar.-->
<!--        {% endfor %}-->
<!--    </table>-->
<!--</div>-->
<!--{% endblock %}-->

secondapp/templates/secondapp/org_dashboard.html
{% extends "secondapp/base.html" %}

{% block title %}{{ organization.name }}{% endblock %}

{% block content %}
Welcome, {{ user.username }}

<p>Name: {{ organization.name }}</p>
<p>Email: {{ organization.email }}</p>
<p>Address: {{ organization.address }}</p>


{% endblock %}

secondapp/templates/secondapp/org_member_list.html
{% extends "secondapp/base.html" %}
{% block title %}Members{% endblock %}

{% block content %}

{{ organization.name }} – Members

<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Skill</th>
        <th>Roles</th>
        <th>Actions</th>
    </tr>
    {% if members %}
        {% for person in members %}
        <tr>
            <td>{{ person.first_name }} {{ person.last_name }}</td>
            <td>{{ person.email }}</td>
            <td>
                {% for skill in person.skills.all %}
                    {{ skill.title }}
                {% empty %}
                    No skills
                {% endfor %}
            </td>
            <td>{% for role in person.roles.all %}
                    {{ role.title }}
                {% empty %}
                    No roles
                {% endfor %}</td>
            <td>
                <a href="{% url 'secondapp:org_member_edit' organization.user.username person.id %}">
                    Edit
                </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td>No members yet</td>
        </tr>
        {% endfor %}
    {% else %}
    <p>No members to display.</p>
    {% endif %}
</table>
{% endblock %}

secondapp/templates/secondapp/person_detail.html
{% extends "secondapp/base.html" %}
{% block title %}{{person.pk}}|{{role}}{% endblock %}
{% block content %}

<div class="action-buttons-top">
    <a href="{% url 'secondapp:person_update' role=role pk=person.pk %}">
        <button type="button">UPDATE - EDIT</button>
    </a>
    <a href="{% url 'secondapp:person_delete' role=role pk=person.pk %}">
        <button type="button">Delete</button>
    </a>
</div>

<h3>Profile page</h3>

<div class="person-details">
    <div class="basic-info">
        <h2>{{ person.first_name }} {{ person.last_name }}</h2>
        <p><strong>Role:</strong> {{ person.voice|default:person.role }}</p>
        <p>email: {{ person.email }}</p>
        {% if person.mobile_number or person.phone_number %}
            <p>phone: {{ person.mobile_number|default:person.phone_number }}</p>
        {% endif %}

        {% if person.skill_level %}
            <p>Skill Level: {{ person.skill_level }}</p>
        {% endif %}

        {% if person.is_active is not None %}
            <p><strong>Is Active:</strong>
                {% if person.is_active %}YES{% else %}NO{% endif %}
            </p>
        {% endif %}
        {% if present or missing %}
            <h3>Rehearsal Attendance</h3>
            <h4>Present at Rehearsals ({{ present|length }}) </h4>

            <h4>Missing from Rehearsals ({{ missing|length }}) </h4>
            <ul>
                {% for rehearsal in missing %}
                    <li>{{ rehearsal.calendar }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if person.date_joined %} <p>Date Joined: {{ person.date_joined }}</p> {% endif %}
    </div>

    <div class="activity">
        {% if person.activity %}
            {% for activity in person.activity.all %}
              <li>
                {{ activity }}
                <a href="{% url 'secondapp:activity_update' role=role pk=activity.pk %}">UPDATE</a> -
                <a href="{% url 'secondapp:activity_confirm_delete' role=role pk=activity.pk %}">DELETE</a>
              </li>
            {% empty %}
                <a href="{% url 'secondapp:activity_form' role=role pk=person.pk %}">Add Activity</a>
            {% endfor %}
        {% endif %}
    </div>

    <div class="personal-info">
        {% if person.shirt_size or person.messenger or person.website %}

            <h3>Personal Information</h3>
            {% if person.shirt_size %}
            <p><strong>Shirt Size:</strong> {{ person.shirt_size }}</p>
            {% endif %}
            {% if person.messenger %}
            <p><strong>Messenger:</strong> {{ person.messenger }}</p>
            {% endif %}
            {% if person.website %}
                <p><strong>Website:</strong> <a href="{{ person.website }}">{{ person.website }}</a></p>
            {% endif %}
        {% endif %}
    </div>

    <div class="musical-background">
        <!-- <h3>Musical Background</h3> -->
        {% if person.biography %}
            <p><strong>Biography:</strong> {{ person.biography }}</p>
        {% endif %}
        {% if person.favorite_works %}
            <p><strong>Favorite Works:</strong> {{ person.favorite_works }}</p>
        {% endif %}
        {% if person.influenced_by %}
            <p><strong>Influenced By:</strong> {{ person.influenced_by }}</p>
        {% endif %}
        {% if person.awards %}
            <p><strong>Awards:</strong> {{ person.awards }}</p>
        {% endif %}
    </div>

    <div class="additional-info">
        {% if person.tags.all %}
            <p><strong>Tags:</strong> {{ person.tags.all|join:", " }}</p>
        {% endif %}
        {% if person.additional_notes %}
            <p><strong>Additional Notes:</strong> {{ person.additional_notes }}</p>
        {% endif %}
    </div>
    <div class="song">
        <table>
            <th>Songs:</th>
            {% for song in song %}
                <tr>
                    <td><a href="{% url 'secondapp:song_detail' song.pk %}"> {{ song.title }} </a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="action-buttons-bottom">
    <a href="{% url 'secondapp:person_update' role=role pk=person.pk %}">
        <button type="button">UPDATE - EDIT</button>
    </a>
    <a href="{% url 'secondapp:person_delete' role=role pk=person.pk %}">
        <button type="button">Delete</button>
    </a>
</div>
{% endblock %}

secondapp/templates/secondapp/person_form.html
{% extends "secondapp/base.html" %}
{% block title %}{% if object %}Edit {{object.pk}}{% else %}Add New{% endif %}{% endblock %}
{% block content %}

<div class="form-header">
    <h1>{% if object %}Edit{% else %}Add{% endif %} {{ role }}</h1>
</div>

<div class="form-container">
    <form method="POST">{% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        </div>

        <div class="form-actions">
            <button type="submit">Save</button>
        </div>
    </form>
</div>

<div class="form-navigation">
    {% if object %}
        <div class="edit-actions">
            <a href="{% url 'secondapp:person_detail' role=role pk=person.pk %}">
                <button type="button">Cancel Edit</button>
            </a>
            <a href="{% url 'secondapp:person_list' role=role %}">
                <button type="button">List of {{ role }}</button>
            </a>
        </div>
    {% else %}
        <div class="create-actions">
            <a href="{% url 'secondapp:person_list' role=role %}"
               onclick="return confirm('You will lose unsaved changes. Continue?')">
                <button type="button">Cancel & Return to List</button>
            </a>
        </div>
    {% endif %}
</div>

{% endblock %}

secondapp/templates/secondapp/person_form2.html
<h2>Update Your Profile</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Profile</button>
</form>

secondapp/templates/secondapp/signup.html
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>

<p><a href="{% url 'secondapp:login' %}">Log In</a></p>

secondapp/templates/secondapp/song_confirm_delete.html
{% extends "secondapp/base.html" %}
{% block title %}{{song.pk}}confirm{% endblock %}
{% block content %}

<div class="delete-confirmation-container">
    <div class="warning-header">
        <h1>Delete Song Confirmation</h1>
    </div>

    <div class="warning-message">
        <p>Are you sure you want to delete this song?</p>
        <div class="item-details">
            <p>Title: {{ song.title }}</p>
            <p>Song ID: {{song.pk}}</p>
            <p>Composer: {{song.composer}}</p>
        </div>
        <div class="warning-note">
            <p>️ This action cannot be undone.</p>
        </div>
    </div>

    <div class="confirmation-form">
        <form method="POST">
            {% csrf_token %}
            <div class="form-actions">
                <div class="danger-action">
                    <button type="submit" class="delete-btn">Yes, delete</button>
                </div>
                <div class="safe-action">
                    <a href="{% url 'secondapp:song_page' owner_username song.pk %}">
                        <button type="button" class="cancel-btn">Cancel</button>
                    </a>
                </div>
            </div>
        </form>
    </div>
    <div class="additional-info">
        <p>This will remove the song from all rehearsals where it was scheduled.</p>
    </div>
</div>

{% endblock %}

secondapp/templates/secondapp/song_detail.html
{% extends "secondapp/base.html" %}
{% block title %}{{song.pk}}Song{% endblock %}
{% block content %}<br>
<a href="{% url 'secondapp:song_list' %}"><button type="button">Songs - Back</button></a>
<h1>{{ song.title }} | {{ song.pk }}</h1>
<p>Composer: <a href="{{ song.composer.get_absolute_url }}">{{ song.composer }}</a></p>
<p>Poet: <a href="{{ song.poet.get_absolute_url }}">{{ song.poet }}</a></p>

<p>Number of copies: {{ song.number_of_copies }}</p>
<p>Number of pages: {{ song.number_of_pages }}</p>
<p>Year: {{ song.year }}</p>

<p>Number of voices: {{ song.number_of_voices }}</p>
<p>Group: {{ song.group }}</p>

<p>Additional notes: {{ song.additional_notes }} </p>

<table>
    <tr><th>songs in rehearsals:</th></tr>
    {% for rehearsal in song.rehearsals.all %}
    <tr>
        <td>
            <a href="{{ rehearsal.get_absolute_url }}">
                {{ rehearsal.calendar|date:"j b Y, G:i" }}
            </a>
        </td>
    </tr>
    {% endfor %}

</table>

<a href="{% url 'secondapp:song_update' song.pk %}"><button type="button">UPDATE EDIT</button></a><br><br>
<a href="{% url 'secondapp:song_delete' song.pk %}"><button type="button">Delete</button></a><br><br>
{% endblock %}

secondapp/templates/secondapp/song_index.html
<html>

<head>
    <title> Songs </title>
</head>

<body>


<a href="{% url 'secondapp:index' %}">Home</a>
<p>Here is a list of all songs:</p>
<table>
 <tr>
    <th> title </th>
    <th> composer </th>
    <th> genre </th>
    <th> link </th>
 </tr>
{% for song in song_list %}
    <tr>
        <td> {{ song.title }} </td>
        <td> {{ song.composer }} </td>
        <td> {{ song.genre }} </td>
        <td><a href="{% url 'secondapp:song_detail' song.pk %}"> Link </a></td>
    </tr>
{% endfor %}
</table>

</body>

</html>